# Site settings
title: SLK Catalyst Partners
email: contact@slkcatalystpartners.com
description: >-
  SLK Catalyst Partners empowers businesses by transforming complex challenges 
  into strategic opportunities, blending proven frameworks with innovative solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://slkcatalystpartners.com" # Update this to your actual domain
permalink: "/:title"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-seo-tag

collections:
  authors:
    output: true
  services:
    output: true
    permalink: /services/:name
  team_members:
    output: true
    permalink: /team/:name
  case_studies:
    output: true
    permalink: /case-studies/:name

# Pagination settings
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 6
  permalink: '/blog/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

# Tag and category pages
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# RSS Feed
feed:
  collections:
    posts:
      path: "/index.xml"

# Navigation
header_pages:
  - private-equity.md
  - approach.md
  - case-studies.md
  - about.md
  - contact.md

# Social media
twitter_username: slkcatalyst
linkedin_username: slk-catalyst-partners

# Google Analytics
google_analytics: # Add your GA tracking ID here

# Footer content
footer_content: "© 2024 SLK Catalyst Partners. All rights reserved."