# General Settings
title: "SLK Catalyst Partners"
email: "contact@slkcatalystpartners.com"
description: >- # this means to ignore newlines until "baseurl:"
  SLK Catalyst Partners empowers businesses by transforming complex challenges 
  into strategic opportunities, blending proven frameworks with innovative solutions.
black_logo_1x: "/assets/images/slk-logo.png"
black_logo_2x: "/assets/images/slk-logo@2x.png"
light_logo_1x: "/assets/images/slk-logo-light.png"
light_logo_2x: "/assets/images/slk-logo-light@2x.png"
copyright_text: "© 2024 SLK Catalyst Partners, part of SLKone"
google_analytics:
  enable: false
  key: ""  # Add your Google Analytics key here if needed

footer_cta:
  title: "Ready to elevate your strategy?"
  subtitle: "Let us be part of your success story. As your strategic partner in innovation and growth, our team is ready to tackle your business challenges. Get in touch, and let's make it happen."
  button_text: "Get in Touch"
  button_url: "/contact"

external_links:
  title: "Our Services"
  links:
    - url: "/private-equity"
      text: "Private Equity Solutions"
    - url: "/approach"
      text: "Our Approach"
    - url: "/case-studies"
      text: "Case Studies"

external_links_02:
  title: "About Us"
  links:
    - url: "/about"
      text: "Our Team"
    - url: "/about#vision"
      text: "Vision & Mission"
    - url: "/about#process"
      text: "Our Process"
    - url: "/contact"
      text: "Contact Us"

external_links_03:
  title: "Resources"
  links:
    - url: "/blog"
      text: "Insights Blog"
    - url: "/faq"
      text: "FAQs"
    - url: "/privacy-policy"
      text: "Privacy Policy"
    - url: "/terms-of-use"
      text: "Terms of Use"

footer_newsletter:
  title: "Stay Informed"
  sub_title: "Subscribe to our newsletter for the latest insights and industry trends."
  subscribe_button_text: "Subscribe"

one_page_nav_settings:
  links:
    - text: "Home"
      url: "#home"
    - text: "Services"
      url: "#services"
    - text: "Approach"
      url: "#approach"
    - text: "Case Studies"
      url: "#case-studies"
    - text: "About Us"
      url: "#about"
    - text: "Contact"
      url: "#contact"

author_page_header:
  header_background_image: "/assets/images/slk-header-bg.jpg"